package sg.whirl.pdp_spring.beans;

import lombok.RequiredArgsConstructor;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

@Component
@RequiredArgsConstructor
public class ConstructorBean {

    public final ConstructorAutowiredBean constructorAutowiredBean1;

    public final String requiredString;

    @Autowired
    public ConstructorBean(ConstructorAutowiredBean bean) {
        // call constructor generated by Lombok
        this(bean, "defaultValue");
    }

}
